services:
  postgres:
    container_name: postgres-sql-tms
    image: postgres
    environment:
      POSTGRES_USER: chamuditha
      POSTGRES_PASSWORD: chamuditha360
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: tms
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-tms
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  jenkins:
    container_name: jenkins-server
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  jenkins-data:
    driver: local
