services:
  mysql:
    container_name: mysql-tms
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: chamuditha360
      MYSQL_DATABASE: tms
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-tms
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local