spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    schema:
      printer:
        enabled: true

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1
  port: 8088